name: Build Docker Images

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Fix Docker Permission
        uses: https://github.com/imlonghao/gitea-runner-docker-permission-fix@main
      - name: Login to Docker Hub
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: git.esd.cc
          username: imlonghao
          password: ${{ secrets.IMLONGHAO_PACKAGES_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6
        with:
          images: git.esd.cc/imlonghao/nbnhhsh_bot
          tags: |
            type=semver,pattern={{version}}
      - name: Build and push
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
